language: ruby
dist: bionic

rvm: 2.5.1

services:
  - redis

cache: bundler

bundler_args: --without development --jobs 3 --retry 3 --deployment

before_install: gem install bundler

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec spec
    - stage: ":ship: it"
      script: make ship
